---
title: "Tooth Morphology"
author: "Corinthia Black"
output: html_document
---

# these lines are necessary for running the file in R markdown
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Programs | Set Directory
```{r}
# phylomorphospace
#install.packages("phytools")
library(phytools)

# PCA visualization
#library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)

# phylogeny
#install.packages("ape")
library(ape)
```

## Load required data
```{r}
# create data frame with morphological data from "ToothMeasurements.txt"
Teeth=read.delim("ToothMeasurements.txt", sep="\t", header = TRUE, row.names = 1)
```

## Principal Components Analysis (PCA): https://tgmstat.wordpress.com/2013/11/28/computing-and-visualizing-pca-in-r/
```{r}
# Run PCA
tooth.pca=prcomp(Teeth, center = TRUE, scale. = TRUE)
# Add species names to PCA data
tooth.pca$names=row.names(Teeth)
summary(tooth.pca)

# Save PCA output to be used in phylomorphospace
# tooth.pca$x = All PC axes; use pca[,c(1,2)] to isolate the 1st and 2nd PC axes (can change numbers to be any other PC axes)
pca=tooth.pca$x
pca.1.2=pca[,c(1,2)]

# Create plot of PC1 and PC2 in ggbiplot
g=ggbiplot(tooth.pca, obs.scale = 1, var.scale = 1, circle = TRUE) + geom_text(aes(label=tooth.pca$names),hjust=0, vjust=0, size=1.5)
g=g+ylim(-4,4)
g=g+xlim(-4,8)
g=g+theme_classic()
print(g)
```

## Import phylogenetic tree (must be newick or nexus file format)
```{r}
# Read nexus phylogeny
tree=read.nexus("catfishes_tree.txt")
# Save one copy of the tree as a phylo type
tree=tree$con_50_majrule
# Root tree to outgroup
tree=root(tree, "KY858079_1_Vandellia_sp_1", resolve.root = TRUE)
# Create list of species names to trim the tree
species=row.names(Teeth)
# Trim the tree to match the list of species and tip labels
trimmed.tree=drop.tip(tree,tree$tip.label[-match(species, tree$tip.label)])
```

## Phylomorphospace: https://besjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/j.2041-210X.2011.00169.x
```{r}
# Find the phylosignal: K>1 = convergence of morphology, K<1 = morphology changes with phylogeny (divergence)
phylosig(trimmed.tree, pca.1.2, method="K", test = TRUE)
# Generate phylomorphospace from trimmed tree and pca coords 
phylomorphospace(trimmed.tree, pca.1.2, label = c("horizontal"), node.size=c(.5,1), xlim=c(-13,8))

### Save Phylomorphospace to working directory as a tiff file
tiff(filename = "PhylomorphoPC1-2.tiff", width = 200, height = 170, units = "mm", res = 300, pointsize = 8)
phylomorphospace(trimmed.tree, pca.1.2, label = c("off"), node.size=c(.5,1))
dev.off()
```
